#!/bin/sh
set -eu

usage() {
  echo "usage: $0 --target <x86_64-unknown-linux-musl|aarch64-unknown-linux-musl> --mode session" >&2
  exit 2
}

TARGET=""
MODE=""
while [ "$#" -gt 0 ]; do
  case "$1" in
    --target) [ "$#" -ge 2 ] || usage; TARGET=$2; shift 2 ;;
    --mode) [ "$#" -ge 2 ] || usage; MODE=$2; shift 2 ;;
    *) usage ;;
  esac
done

case "$TARGET" in
  x86_64-unknown-linux-musl|aarch64-unknown-linux-musl) ;;
  *) usage ;;
esac
[ "$MODE" = "session" ] || usage

ROOT_DIR=$(CDPATH= cd -- "$(dirname -- "$0")/.." && pwd)
FIXTURE_DIR="$ROOT_DIR/crates/hermito/tests/fixtures/tuf"
CONFIG_DIR="$FIXTURE_DIR/config"
SETTINGS="$CONFIG_DIR/settings.toml"
OUTPUT_DIR="$FIXTURE_DIR/generated/$TARGET"
TARGETS_INPUT="$OUTPUT_DIR/targets-input"

[ -f "$SETTINGS" ] || { echo "missing fixture settings: $SETTINGS" >&2; exit 1; }
[ -f "$CONFIG_DIR/root.json" ] || { echo "missing signed test root" >&2; exit 1; }

TOOL_VERSION=$(tuftool --version 2>/dev/null || true)
if [ "$TOOL_VERSION" != "tuftool 0.17.0" ]; then
  cargo +1.94.1 install tuftool --version 0.17.0 --locked
fi

rustup target add "$TARGET" >/dev/null
HOST_TRIPLE=$(rustc -vV | sed -n 's/^host: //p')
RUST_LLD="$(rustc --print sysroot)/lib/rustlib/$HOST_TRIPLE/bin/rust-lld"
if [ -x "$RUST_LLD" ]; then
  case "$TARGET" in
    x86_64-unknown-linux-musl) export CARGO_TARGET_X86_64_UNKNOWN_LINUX_MUSL_LINKER="$RUST_LLD" ;;
    aarch64-unknown-linux-musl) export CARGO_TARGET_AARCH64_UNKNOWN_LINUX_MUSL_LINKER="$RUST_LLD" ;;
  esac
fi

cargo build --manifest-path "$ROOT_DIR/Cargo.toml" -p hermito-remote --release --target "$TARGET"
rm -rf "$OUTPUT_DIR"
mkdir -p "$TARGETS_INPUT" "$OUTPUT_DIR/repository"
cp "$ROOT_DIR/target/$TARGET/release/hermito-remote" "$TARGETS_INPUT/hermito-remote-$TARGET"

tuftool create \
  --key "$CONFIG_DIR/targets-key.pem" \
  --key "$CONFIG_DIR/snapshot-key.pem" \
  --key "$CONFIG_DIR/timestamp-key.pem" \
  --outdir "$OUTPUT_DIR/repository" \
  --root "$CONFIG_DIR/root.json" \
  --snapshot-expires "2030-01-01T00:00:00Z" \
  --snapshot-version 1 \
  --add-targets "$TARGETS_INPUT" \
  --targets-expires "2030-01-01T00:00:00Z" \
  --targets-version 1 \
  --timestamp-expires "2030-01-01T00:00:00Z" \
  --timestamp-version 1

# tuftool writes consistent-snapshot targets as links into the input directory.
# Materialize them before removing the staging directory so fixtures are self-contained.
for SIGNED_TARGET in "$OUTPUT_DIR/repository/targets/"*; do
  cp -L "$SIGNED_TARGET" "$SIGNED_TARGET.materialized"
  mv "$SIGNED_TARGET.materialized" "$SIGNED_TARGET"
done

cp "$CONFIG_DIR/root.json" "$OUTPUT_DIR/repository/root.json"
printf '%s\n' "TEST-ONLY repository generated by tuftool 0.17.0 for $TARGET" > "$OUTPUT_DIR/TEST_ONLY"
rm -rf "$TARGETS_INPUT"

echo "$OUTPUT_DIR/repository"
